// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { CheckBox, StandardListView, StandardButton, Button, Slider, VerticalBox, ScrollView } from "std-widgets.slint";


export component App inherits Window {
    preferred-width: 700px;
    preferred-height: 500px;
    title: @tr("Testing File dirs");
    in-out property<string> dir;
    out property <int> iterationLimit;
    in property <[string]> data;

    callback open-file-dialog;
    callback copy-activated();
    callback paste-activated();

    MenuBar {
        Menu {
            title: @tr("MenuBar" => "Edit");
            MenuItem { title: @tr("MenuBar" => "Copy"); 
            activated => { root.copy-activated(); }
            }
            
            MenuItem { title: @tr("MenuBar" => "Paste");
            activated => { root.paste-activated(); }
            }
        }
    }


    
    if dir.is-empty : VerticalLayout {
        Button { 
        text: "Pick a directory";
        clicked => {root.open-file-dialog()}
        }
        
        
        slider := Slider {
            changed(value) => {
                debug("Slider value changed to {}", value);
                root.iterationLimit = value;
            }
            step: 1;            
            minimum: 0;
            maximum: 15;
            value: 1;
        }
        
    }           
    if !dir.is-empty : VerticalBox {
        Text {
            text: "Selected Directory: " + dir;
        }
        ScrollView {
            vertical-scrollbar-policy: always-on;
            viewport-height: 500px;
            viewport-width: 100px;
            VerticalBox { 
            for dt in data : HorizontalLayout {
                CheckBox {
                    checked: true;
                    padding-right: 10px;
                }
                Text { 
                    text: dt;
                }
            }
            }   
        
        }
    
    }
}
