export component GraphWindow inherits Window {
    preferred-width: 700px;
    preferred-height: 500px;
    title: @tr("Testing graphs dirs");
    in-out property<image> graph;

    callback clicked(x: length, y: length);

    global-input := TouchArea {
        clicked => {
            root.clicked(global-input.mouse-x, global-input.mouse-y);
        }
        Image {
            source: graph;
        }
    }

    
}
