export component GraphWindow inherits Window {
    preferred-width: 700px;
    preferred-height: 500px;

    title: @tr("Testing custom UI");
    in-out property<image> graph;

    callback clicked(x: length, y: length);

    changed width => {
        dimensions-changed(self.width, self.height);
    }
    changed height => {
        dimensions-changed(self.width, self.height);
    }
    callback dimensions-changed(width: length, height: length);
    

    global-input := TouchArea {
        clicked => {
            root.clicked(global-input.mouse-x, global-input.mouse-y);
        }
        moved => {
            if global-input.mouse-x > root.width || global-input.mouse-x < 0 || global-input.mouse-y > root.height || global-input.mouse-y < 0 {
                root.title = "Out of bounds";
            } else {
                root.title = "Custom UI";
            }
        }
        
        img := Image {
            source: graph;
            x: 0;
            y: 0;
        }

    }

    
}
